# Generated by Django 5.1.1 on 2024-10-17 10:58

from django.db import migrations, models

def create_default_simulation_status(apps, schema_editor):
    SimulationStatus = apps.get_model('your_app_name', 'SimulationStatus')
    SimulationStatus.objects.create(simulation_status=False)


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_status', models.BooleanField(default=False)),
            ],
        ),
        
        migrations.RunPython(create_default_simulation_status),
    ]
