# Generated by Django 5.1.1 on 2024-10-17 11:06

from django.db import migrations

def create_default_simulation_status(apps, schema_editor):
    SimulationStatus = apps.get_model('driver', 'SimulationStatus')
    SimulationStatus.objects.create(simulation_status=False)

class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_simulationstatus'),
    ]

    operations = [
        migrations.RunPython(create_default_simulation_status),
    ]
