# Generated by Django 5.1.1 on 2024-10-17 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='driver_feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_rating',
            new_name='rating',
        ),
    ]
