version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn atlan_backend.asgi:application -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - logistics_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    networks:
      - logistics_network

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - logistics_network

  redis:
    image: redis:alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    # command: sh -c "sysctl -w vm.overcommit_memory=1 && redis-server /usr/local/etc/redis/redis.conf"
    privileged: true
    ports:
      - "6379:6379"
    networks:
      - logistics_network

  celery:
    build: .
    command: celery -A atlan_backend worker --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - db
    networks:
      - logistics_network

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  logistics_network:
    driver: bridge