# Generated by Django 5.1.1 on 2024-10-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20241017_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationstatus',
            name='simulation_status',
            field=models.BooleanField(default=True),
        ),
    ]
