# Generated by Django 5.1.1 on 2024-10-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('booking', '0002_booking_otp_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='available_bookings',
            field=models.ManyToManyField(blank=True, related_name='available_drivers', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='total_rides',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
